import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,freshSave,sanitizeSave,CHARACTERS,WEAPONS,buyAttack,buyStat,isUnlocked} from '../dist/game.js';
function seeded(seed=17){return()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
test('four initial survivors, locked Naia, native attack pools',()=>{const s=freshSave();assert.equal(CHARACTERS.filter(c=>isUnlocked(s,c.id)).length,4);for(const c of CHARACTERS)assert.equal(s.characters[c.id].unlocked.length,3);assert.throws(()=>new Game('naia','lash',s));assert.throws(()=>new Game('amaris','fireball',s));});
test('attack purchase is per character, selectable at start and in level-up pool',()=>{const s=freshSave();s.gold=1000;assert.equal(buyAttack(s,'amaris','fireball'),true);assert.equal(s.gold,840);assert.equal(buyAttack(s,'amaris','fireball'),false);assert.equal(s.characters.nyxara.unlocked.includes('fireball'),false);const g=new Game('amaris','fireball',s);assert.equal(g.weapons[0].id,'fireball');assert.ok(g.pool.includes('fireball'));assert.equal(buyAttack(s,'amaris','lash'),false);assert.equal(buyAttack(s,'naia','fireball'),false);s.wins=1;assert.equal(buyAttack(s,'amaris','lash'),true);assert.doesNotThrow(()=>new Game('naia','lash',s));});
test('permanent health and damage cannot spend past gold or rank cap',()=>{const s=freshSave();assert.equal(buyStat(s,'ignara','health'),false);s.gold=500;assert.equal(buyStat(s,'ignara','health'),true);assert.equal(s.gold,430);assert.equal(new Game('ignara','fireball',s).maxHp,125);assert.equal(buyStat(s,'ignara','attack'),true);assert.ok(new Game('ignara','fireball',s).damage>1.12);s.characters.ignara.health=10;assert.equal(buyStat(s,'ignara','health'),false);});
test('three unique randomized choices, upgrade pause, six-slot and five-rank limits',()=>{const s=freshSave(),g=new Game('ignara','fireball',s,seeded());let different=new Set();for(let i=0;i<30;i++){const c=g.makeChoices();assert.equal(c.length,3);assert.equal(new Set(c.map(x=>x.type+x.id)).size,3);assert.ok(c.some(x=>x.type==='weapon'));assert.ok(c.some(x=>x.type==='stat'));different.add(c.map(x=>x.id).join());}assert.ok(different.size>5);g.xp=g.nextXp;g.checkLevel();const before=g.time;g.step(.05,{x:1,y:0});assert.equal(g.time,before);assert.equal(g.state,'levelup');assert.equal(g.choose(0),true);assert.equal(g.state,'playing');g.pool=WEAPONS.map(w=>w.id);g.weapons=WEAPONS.slice(0,6).map(w=>({id:w.id,level:5,cd:1}));assert.ok(g.makeChoices().every(x=>x.type==='stat'));});
test('pause stops all clocks; real-time milestones spawn once at 5, 10, and 15 minutes',()=>{const s=freshSave(),g=new Game('ignara','fireball',s);g.state='paused';g.step(.05);assert.equal(g.time,0);g.state='playing';for(const [t,stage] of [[300,1],[600,2],[900,3]]){g.time=t-.025;g.enemies=[];g.step(.05);assert.ok(g.milestones.includes(stage));assert.equal(g.enemies.filter(e=>e.stage===stage).length,1);g.step(.05);assert.equal(g.enemies.filter(e=>e.stage===stage).length,1);}assert.ok(g.finalSpawned);});
test('boss death unlocks Naia and rewards settle exactly once',()=>{const s=freshSave(),g=new Game('amaris','katana',s,seeded());g.time=960;const boss=g.spawn('final',3);g.hit(boss,1e9,'steel');assert.equal(g.state,'won');assert.equal(g.settle(s),true);assert.equal(s.wins,1);assert.equal(s.runs,1);assert.equal(s.gold,450);assert.equal(g.settle(s),false);assert.equal(s.gold,450);assert.equal(isUnlocked(s,'naia'),true);assert.deepEqual(sanitizeSave(JSON.parse(JSON.stringify(s))),s);});
test('corrupt save fields cannot unlock invalid attacks or negative purchases',()=>{const s=sanitizeSave({version:1,gold:-50,wins:0,characters:{amaris:{health:Infinity,attack:999,unlocked:['oops','lash','fireball']}}});assert.equal(s.gold,0);assert.equal(s.characters.amaris.health,0);assert.equal(s.characters.amaris.attack,10);assert.ok(!s.characters.amaris.unlocked.includes('lash'));assert.ok(!s.characters.amaris.unlocked.includes('oops'));assert.ok(s.characters.amaris.unlocked.includes('fireball'));});
test('every weapon can deal damage and each character can complete a combat cycle',()=>{const s=freshSave();s.wins=1;for(const c of CHARACTERS){s.characters[c.id].unlocked=WEAPONS.map(w=>w.id);for(const w of WEAPONS){const g=new Game(c.id,w.id,s,seeded());const e=g.spawn();e.x=g.x+(w.kind==='orbit'?100:30);e.y=g.y;e.hp=e.maxHp=10000;g.rebuildGrid();g.cast(g.weapons[0]);for(let i=0;i<20;i++)g.step(.05);assert.ok(e.hp<10000,`${c.id}/${w.id} should hit`);assert.ok(Number.isFinite(g.hp));}}});
test('15 minute simulation preserves finite state, milestone timing and bounded mobs',()=>{const s=freshSave(),g=new Game('nyxara','frost',s,seeded());g.maxHp=g.hp=1e8;for(let i=0;i<18002;i++){if(g.state==='levelup')g.choose(0);g.step(.05,{x:Math.cos(i*.0017),y:Math.sin(i*.0017)});g.events.length=0;}assert.ok(g.time>=899);assert.ok(g.milestones.includes(1)&&g.milestones.includes(2));assert.ok(g.enemies.length<=285);assert.ok(Number.isFinite(g.x)&&Number.isFinite(g.y)&&Number.isFinite(g.hp));});
